# Use distribution Ubuntu 18.04 Bionic
dist: bionic

language: python

python:
    - "3.6"

# Handle dependencies in separate directory.
before_install:
    - DEPS_DIR="${HOME}/deps"
    - mkdir -p "${DEPS_DIR}"
    - cd "${DEPS_DIR}"

# Install necessary packages.
install:
# Install a recent version of CMake
    - |
        CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz"
        if [ ! -f ${DEPS_DIR}/cmake/bin/cmake ] ; then mkdir -p cmake ; travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake ; fi
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}

    # Install a recent version of the Protobuf
    - |
        PROTOBUF_URL="https://github.com/google/protobuf/releases/download/v3.2.0/protobuf-cpp-3.2.0.tar.gz"
        if [ ! -f ${DEPS_DIR}/protobuf/install/bin/protoc ] ; then mkdir -p protobuf ; travis_retry wget --no-check-certificate --quiet -O - ${PROTOBUF_URL} | tar --strip-components=1 -xz -C protobuf ; cd protobuf ; ./configure --prefix=${DEPS_DIR}/protobuf/install ; make ; make install ; fi
        export PATH=${DEPS_DIR}/protobuf/install/bin:${PATH}

    # Install proto2cpp for doxygen
    - |
        PROTO2CPP_URL="https://github.com/OpenSimulationInterface/proto2cpp.git"
        if [ ! -f ${DEPS_DIR}/proto2cpp ] ; then mkdir -p proto2cpp ; git clone ${PROTO2CPP_URL} ${DEPS_DIR}/proto2cpp ; fi
        
    - sudo apt-get install python3-pip libprotobuf-dev protobuf-compiler libenchant1c2a doxygen doxygen-doc doxygen-latex doxygen-gui graphviz
    - pip install sphinx_rtd_theme
    - pip install sphinx_git
    - pip install sphinxcontrib.spelling
    - pip install progress
    - pip install breathe
    - pip install exhale
    - pip install --upgrade recommonmark

# Addons necessary for documentation.
addons:
    apt:
        packages:
            - python3-sphinx

# Change directory back to default build directory.
before_script:
    - cd "${TRAVIS_BUILD_DIR}"

# Run the build script and generate documentation.
script:
    # Install osi-validation to be parsed by sphinx
    - git clone https://github.com/michaeljones/breathe.git
    - git clone https://github.com/OpenSimulationInterface/osi-visualizer.git
    - git clone https://github.com/OpenSimulationInterface/osi-validation.git
    - git clone https://github.com/OpenSimulationInterface/open-simulation-interface.git
    - git clone https://github.com/OpenSimulationInterface/proto2cpp.git
    - git clone https://github.com/OpenSimulationInterface/osi-sensor-model-packaging.git

    # Generate the OSI doxygen documentation so that it can be parsed by breath
    - cd open-simulation-interface
    - mkdir build
    - cd build
    - cmake -D CMAKE_PREFIX_PATH:PATH=${DEPS_DIR}/protobuf/install -D CMAKE_INSTALL_PREFIX:PATH=${TESTINST_DIR} ..
    - cmake --build .
    - echo "GENERATE_XML = YES" >> Doxyfile
    - doxygen
    - cd ..
    - cp -rf open-simulation-interface/doc/images/* open-simulation-interface/doc/xml/

    # Check spelling mistakes
    # - make spelling

    # Check if all links are working
    # - make linkcheck

    # Build the html pages
    - make html

# Deploy the documentation on github (only for master branch).
deploy:
    provider: pages
    skip_cleanup: true
    local_dir: doc/html
    keep-history: true
    github_token: ${GH_REPO_TOKEN}
    on: 
      branch: master 
